- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy website files
  copy:
    src: index.html
    dest: "{{ site_root }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
  notify: restart nginx
