---
- name: Install Kibana
  hosts: fhm42otmgol83hkoat8o.auto.internal
  become: yes
  vars:
    es_pass: ""

  tasks:
    - name: Add Elastic repository from Yandex mirror
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
        state: present
        filename: "elastic"

    - name: Install Kibana package
      apt:
        name: kibana
        state: present
        update_cache: yes

    - name: Create Kibana configuration
      copy:
        content: |
          server.port: 5601
          server.host: "0.0.0.0"
          
          elasticsearch.hosts: ["http:epd7897i4u5irhm7vgu4.auto.internal:9200"]
          elasticsearch.username: "kibana_system_user"
          elasticsearch.password: "{{ es_pass }}"
        dest: /etc/kibana/kibana.yml
        owner: kibana
        group: kibana
        mode: 0644
      notify: restart kibana

    - name: Start and enable Kibana service
      systemd:
        name: kibana
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for Kibana to start
      wait_for:
        port: 5601
        delay: 10
        timeout: 60

    - name: Show Kibana status
      debug:
        msg: "Kibana is running on http://{{ inventory_hostname }}:5601"

  handlers:
    - name: restart kibana
      systemd:
        name: kibana
        state: restarted